import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { LatexProvider } from "@/context/LatexContext";
import Sidebar from "@/components/side-bar";
import { Providers } from "../providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <Providers>
      <LatexProvider>
        <div className="flex ">
          <Sidebar />
          <div className="w-full">
            {children}
          </div>
        </div>
      </LatexProvider>

    </Providers>

  );
}
